#!/usr/bin/env python
# -*- coding: utf-8 -*-

doctors = ['Abraham Mamrelund',
           'li Baba',
           'lfonso Trendy',
           'lfred Balle',
           'ngelica Houston',
           'sger Dubonnet',
           'eelzebub Komseda',
           'ent Tonse',
           'itten og Trold',
           'Bjarne Goldbæk',
           'Broder Salsa',
           'Casey og Jürgen Klins',
           'Casper',
           'Ciarta Johnnysdottir',
           'Claes Gynhjalter',
           'Claes Jakob Baunspieler',
           'Claudius Mendelsohn',
           'Conan Lurbakke',
           'Cornelius Heinesen',
           'Didrik Amundsen',
           'Dobbey Slenger',
           'Doktor Doktor',
           'Dino Stram',
           'Dåsen Allan',
           'Eduardo Havana Goebbels',
           'Ejnar Brobrille',
           'Elmo Gotlieb Våge',
           'Fissirul Lohmann',
           'Flemming Timmernik',
           'Fyrst Walter',
           'Gentleman Finn',
           'Gerda',
           'Gynhter Renouard',
           'Gøkhan Appel',
           'Harley Løvstik',
           'Hasle Ryberæv',
           'Henning',
           'Humphrey Desmond Tutu',
           'Hr. Vællemand',
           'Ibiza Polar',
           'Ingmar Hildelyst',
           'Jakob Majkilde',
           'Jeppe Velling',
           'Jericho Lala',
           'Joakim Tüddel',
           'Johannes Hot',
           'Johannes Ludvig',
           'John Gringo',
           'Julius Hazard',
           'Kenneth',
           'Kenneth Kiwistone',
           'Klovnen Liljan',
           'Lars Krimi',
           'Lars Pejsekammer',
           'Laughing Eagle',
           'Lennart Bertelsen',
           'Mario Rawanda',
           'Massimo Blanco',
           'Maximillian Syfax',
           'Molle Bedstefik',
           'Newton Dynamose',
           'Niels Esb',
           'Niller Sas Ungdom',
           'Norm',
           'Otis Mallebrok',
           'Pelle Klumpfeber',
           'Per DeBurg',
           'Peter Schmeichel',
           'Plasma Amelund',
           'Preben Hmmm',
           'Renè D. Seance',
           'Rusty Mandolini',
           'Saltefanden',
           'Satan',
           'Satire-John',
           'Scottie',
           'Sidney Kreutzfeldt',
           'Silas Gnom',
           'Simba',
           'Sixten Bo Maneater',
           'Skat Henningsen',
           'Smokie Spartacus',
           'Steegan Flint Persson',
           'Svenne Olota',
           'Tanja',
           'Terkel Algevind',
           'Thøger Messias Vorte',
           'Tim Staniole',
           'Torben Eler Murmark',
           'Tore Ellen Hanhøj',
           'Verner Lohals',
           'Wesley Snipes',
           'Ånden i vasken', ]
